TRUNCATE SCHEMA public AND COMMIT;

DROP TABLE ADM_Acciones;
DROP TABLE ADM_Controllers;
DROP TABLE ADM_ER_rol_funcionalidad;
DROP TABLE ADM_ER_usuarios_roles;  
DROP TABLE ADM_Funcionalidades;
DROP TABLE ADM_Roles;  
DROP TABLE ADM_Usuarios;   
DROP TABLE ADM_Vistas;   
DROP TABLE ADM_GenericRepo;
DROP TABLE ADM_GenericRepoRel;

COMMIT;


CREATE TABLE ADM_Acciones(
    id_accion int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null UNIQUE,
    accion varchar(50) NOT NULL);
    

CREATE TABLE ADM_Roles(
    id_rol int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null UNIQUE,
    rol varchar(50) NOT NULL,
    fec_mod datetime NOT NULL);
    
CREATE TABLE ADM_Usuarios(
    id_usuario int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null UNIQUE,
    usuario varchar(50) NOT NULL,
    fec_mod datetime NOT NULL);

 
CREATE TABLE ADM_Controllers(
    id_controller int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null UNIQUE,
    controller varchar(50) NOT NULL);
    
CREATE TABLE ADM_ER_usuarios_roles(
    id_usuario int NOT NULL,
    id_rol int NOT NULL,
    FOREIGN KEY (id_rol) REFERENCES ADM_Roles(id_rol),
    FOREIGN KEY (id_usuario) REFERENCES ADM_Usuarios(id_usuario));


CREATE TABLE ADM_Funcionalidades(
    id_func int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null UNIQUE,
    id_controller int NOT NULL,
    id_accion int NOT NULL,
    FOREIGN KEY (id_controller) REFERENCES ADM_Controllers(id_controller),
    FOREIGN KEY (id_accion) REFERENCES ADM_Acciones(id_accion));


CREATE TABLE ADM_ER_rol_funcionalidad(
    id_rol int NOT NULL,
    id_func int NOT NULL,
    FOREIGN KEY (id_rol) REFERENCES ADM_Roles(id_rol),
    FOREIGN KEY (id_func) REFERENCES ADM_Funcionalidades(id_func));

 CREATE TABLE ADM_GenericRepo(
    id int GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1) not null UNIQUE,
    name varchar(50) NOT NULL);
    
CREATE TABLE ADM_GenericRepoRel(
    id int GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1) not null UNIQUE,
    id_rel int NOT NULL,
    FOREIGN KEY (id_rel) REFERENCES ADM_GenericRepo(id));


--
--ALTER TABLE ADM_ER_rol_funcionalidad  ADD  CONSTRAINT FK_ADM_ER_rol_vista_acc_ADM_ER_vistas_acciones FOREIGN KEY(id_vis_acc)
--REFERENCES ADM_Funcionalidad (id_vis_acc)
--
--ALTER TABLE ADM_ER_rol_funcionalidad  CONSTRAINT FK_ADM_ER_rol_vista_acc_ADM_ER_vistas_acciones
--
--ALTER TABLE ADM_ER_rol_funcionalidad  ADD  CONSTRAINT FK_ADM_ER_rol_vista_acc_ADM_Roles FOREIGN KEY(id_rol)
--REFERENCES ADM_Roles (id_rol)
--
--ALTER TABLE ADM_ER_rol_funcionalidad  CONSTRAINT FK_ADM_ER_rol_vista_acc_ADM_Roles
--
--ALTER TABLE ADM_ER_usuarios_roles  ADD  CONSTRAINT FK_ADM_ER_usuarios_roles_ADM_Roles FOREIGN KEY(id_rol)
--REFERENCES ADM_Roles (id_rol)
--
--ALTER TABLE ADM_ER_usuarios_roles  CONSTRAINT FK_ADM_ER_usuarios_roles_ADM_Roles
--
--ALTER TABLE ADM_ER_usuarios_roles  ADD  CONSTRAINT FK_ADM_ER_usuarios_roles_ADM_Usuarios FOREIGN KEY(id_usuario)
--REFERENCES ADM_Usuarios (id_usuario)
--
--ALTER TABLE ADM_ER_usuarios_roles  CONSTRAINT FK_ADM_ER_usuarios_roles_ADM_Usuarios
--
--ALTER TABLE ADM_Funcionalidad  ADD  CONSTRAINT FK_ADM_ER_vistas_acciones_ADM_Acciones FOREIGN KEY(id_accion)
--REFERENCES ADM_Acciones (id_accion)
--
--ALTER TABLE ADM_Funcionalidad  CONSTRAINT FK_ADM_ER_vistas_acciones_ADM_Acciones
--
--ALTER TABLE ADM_Funcionalidad  ADD  CONSTRAINT FK_ADM_ER_vistas_acciones_ADM_Vistas FOREIGN KEY(id_vista)
--REFERENCES ADM_Vistas (id_vista)
--
--ALTER TABLE ADM_Funcionalidad  CONSTRAINT FK_ADM_ER_vistas_acciones_ADM_Vistas

